#tests3.csv hat nur 8 Zeilen (zum ausprobieren, günstig und schnell) 
#test2.csv hat "alles" was von der Datenvorverarbeitung übergeben wird.
#test4.csv wurde via Script erzeugt (transform_to_llm_prompt.py) und fasst zusammengehörige INjects zu einem Datensazu zusammen
prompts:
  - file://prompts_withoutmetrics.txt
providers:
#  - openai:gpt-3.5-turbo-1106
 - openai:gpt-4o-mini
  # - openai:gpt-4o

defaultTest:
  assert:
    - type: python
      value: file://../assert.py

tests: file://../_abvariation/test_v1.csv

